### ISSUE TITLE
Chain Converter not working

### ISSUE THREAD

**Issue by pdobrigkeit** [digilist/SnakeDumper#26]
The Chain converter is not working for me. It just gets an array of strings, but those are never instantiated as converters.

Config:
```
    converters:
      name:
        - Chain:
          - Company
          - Faker:
              formatter: "companySuffix"
```

Output:
```
PHP Fatal error:  Uncaught Error: Call to a member function convert() on string in /application/vendor/digilist/snakedumper/src/Converter/ChainConverter.php:43
Stack trace:
#0 /application/vendor/digilist/snakedumper/src/Converter/Service/DataConverter.php(34): Digilist\SnakeDumper\Converter\ChainConverter->convert()
#1 /application/vendor/digilist/snakedumper/src/Dumper/Sql/Dumper/TableContentsDumper.php(142): Digilist\SnakeDumper\Converter\Service\DataConverter->convert()
#2 /application/vendor/digilist/snakedumper/src/Dumper/Sql/Dumper/TableContentsDumper.php(84): Digilist\SnakeDumper\Dumper\Sql\Dumper\TableContentsDumper->dumpTableContent()
#3 /application/vendor/digilist/snakedumper/src/Dumper/SqlDumper.php(82): Digilist\SnakeDumper\Dumper\Sql\Dumper\TableContentsDumper->dumpTable()
#4 /application/vendor/digilist/snakedumper/src/Dumper/SqlDumper.php(46): Digilist\SnakeDumper\Dumper\SqlDumper->dumpTables()
#5 /application/vendor/digilist/snakedumper/src/Command/DumpCommand.php(56): Digilist\SnakeDumper\Dumper\SqlDumper->d in /application/vendor/digilist/snakedumper/src/Converter/ChainConverter.php on line 43
```

**Comment by pdobrigkeit** [comment]
I figured it out as it seems from the source code...

```
    converters:
      name:
        - Company
        - Faker:
          formatter: "companySuffix"
```

to automatically create a chain, but this is not what i want... I would wand to combine the output of the two...
